# Use the official Nginx image as the base image
FROM nginx:latest

# Set the environment variable for the API base URL
ENV API_BASE_URL=https://prueba-plexus-backend.serverbb.online

# Remove the default Nginx configuration
RUN rm -rf /etc/nginx/conf.d/default.conf

# Copy the built Vue app files into the Nginx web root
COPY ./dist /usr/share/nginx/html

# Copy the custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/

# Expose port 80 for Nginx
EXPOSE 80

# Start Nginx when the container runs
CMD ["nginx", "-g", "daemon off;"]
